package com.thinqq.qsports.server.process.util;

import java.util.ArrayList;
import java.util.List;

import com.thinqq.qsports.persistence.dto.CountryVo;


public class CountryList {
	private static List<CountryVo> listCountry = new ArrayList<CountryVo>();
	public static List<CountryVo> getListCountry(){
		
		return listCountry;
		
	}
	static {
//		listCountry.add(new CountryVo("AF","AFGHANISTAN"));
//				listCountry.add(new CountryVo("AX","ALAND_ISLANDS"));
//				listCountry.add(new CountryVo("AL","ALBANIA"));
//				listCountry.add(new CountryVo("DZ","ALGERIA"));
//				listCountry.add(new CountryVo("AS","AMERICAN_SAMOA"));
//				listCountry.add(new CountryVo("AD","ANDORRA"));
//				listCountry.add(new CountryVo("AO","ANGOLA"));
//				listCountry.add(new CountryVo("AI","ANGUILLA"));
//				listCountry.add(new CountryVo("AQ","ANTARCTICA"));
//				listCountry.add(new CountryVo("AG","ANTIGUA_AND_BARBUDA"));
//				listCountry.add(new CountryVo("AR","ARGENTINA"));
//				listCountry.add(new CountryVo("AM","ARMENIA"));
//				listCountry.add(new CountryVo("AW","ARUBA"));
				listCountry.add(new CountryVo("AU","Australia"));
//				listCountry.add(new CountryVo("AT","AUSTRIA"));
//				listCountry.add(new CountryVo("AZ","AZERBAIJAN"));
//				listCountry.add(new CountryVo("BS","BAHAMAS"));
//				listCountry.add(new CountryVo("BH","BAHRAIN"));
				listCountry.add(new CountryVo("BD","Bangladesh"));
//				listCountry.add(new CountryVo("BB","BARBADOS"));
//				listCountry.add(new CountryVo("BY","BELARUS"));
//				listCountry.add(new CountryVo("BE","BELGIUM"));
//				listCountry.add(new CountryVo("BZ","BELIZE"));
//				listCountry.add(new CountryVo("BJ","BENIN"));
//				listCountry.add(new CountryVo("BM","BERMUDA"));
//				listCountry.add(new CountryVo("BT","BHUTAN"));
//				listCountry.add(new CountryVo("BO","BOLIVIA_PLURINATIONAL_STATE_OF"));
//				listCountry.add(new CountryVo("BQ","BONAIRE_SINT_EUSTATIUS_AND_SABA"));
//				listCountry.add(new CountryVo("BA","BOSNIA_AND_HERZEGOVINA"));
//				listCountry.add(new CountryVo("BW","BOTSWANA"));
//				listCountry.add(new CountryVo("BV","BOUVET_ISLAND"));
//				listCountry.add(new CountryVo("BR","BRAZIL"));
//				listCountry.add(new CountryVo("IO","BRITISH_INDIAN_OCEAN_TERRITORY"));
//				listCountry.add(new CountryVo("BN","BRUNEI_DARUSSALAM"));
//				listCountry.add(new CountryVo("BG","BULGARIA"));
//				listCountry.add(new CountryVo("BF","BURKINA_FASO"));
//				listCountry.add(new CountryVo("BI","BURUNDI"));
//				listCountry.add(new CountryVo("KH","CAMBODIA"));
//				listCountry.add(new CountryVo("CM","CAMEROON"));
				listCountry.add(new CountryVo("CA","Canada"));
//				listCountry.add(new CountryVo("CV","CAPE_VERDE"));
//				listCountry.add(new CountryVo("KY","CAYMAN_ISLANDS"));
//				listCountry.add(new CountryVo("CF","CENTRAL_AFRICAN_REPUBLIC"));
//				listCountry.add(new CountryVo("TD","CHAD"));
//				listCountry.add(new CountryVo("CL","CHILE"));
//				listCountry.add(new CountryVo("CN","CHINA"));
//				listCountry.add(new CountryVo("CX","CHRISTMAS_ISLAND"));
//				listCountry.add(new CountryVo("CC","COCOS_KEELING_ISLANDS"));
//				listCountry.add(new CountryVo("CO","COLOMBIA"));
//				listCountry.add(new CountryVo("KM","COMOROS"));
//				listCountry.add(new CountryVo("CG","CONGO"));
//				listCountry.add(new CountryVo("CD","CONGO_THE_DEMOCRATIC_REPUBLIC_OF_THE"));
//				listCountry.add(new CountryVo("CK","COOK_ISLANDS"));
//				listCountry.add(new CountryVo("CR","COSTA_RICA"));
//				listCountry.add(new CountryVo("CI","COTE_D_IVOIRE"));
//				listCountry.add(new CountryVo("HR","CROATIA"));
//				listCountry.add(new CountryVo("CU","CUBA"));
//				listCountry.add(new CountryVo("CW","CURACAO"));
//				listCountry.add(new CountryVo("CY","CYPRUS"));
//				listCountry.add(new CountryVo("CZ","CZECH_REPUBLIC"));
//				listCountry.add(new CountryVo("DK","DENMARK"));
//				listCountry.add(new CountryVo("DJ","DJIBOUTI"));
//				listCountry.add(new CountryVo("DM","DOMINICA"));
//				listCountry.add(new CountryVo("DO","DOMINICAN_REPUBLIC"));
//				listCountry.add(new CountryVo("EC","ECUADOR"));
//				listCountry.add(new CountryVo("EG","EGYPT"));
//				listCountry.add(new CountryVo("SV","EL_SALVADOR"));
//				listCountry.add(new CountryVo("GQ","EQUATORIAL_GUINEA"));
//				listCountry.add(new CountryVo("ER","ERITREA"));
//				listCountry.add(new CountryVo("EE","ESTONIA"));
//				listCountry.add(new CountryVo("ET","ETHIOPIA"));
//				listCountry.add(new CountryVo("FK","FALKLAND_ISLANDS_MALVINAS"));
//				listCountry.add(new CountryVo("FO","FAROE_ISLANDS"));
//				listCountry.add(new CountryVo("FJ","FIJI"));
//				listCountry.add(new CountryVo("FI","FINLAND"));
//				listCountry.add(new CountryVo("FR","FRANCE"));
//				listCountry.add(new CountryVo("GF","FRENCH_GUIANA"));
//				listCountry.add(new CountryVo("PF","FRENCH_POLYNESIA"));
//				listCountry.add(new CountryVo("TF","FRENCH_SOUTHERN_TERRITORIES"));
//				listCountry.add(new CountryVo("GA","GABON"));
//				listCountry.add(new CountryVo("GM","GAMBIA"));
//				listCountry.add(new CountryVo("GE","GEORGIA"));
//				listCountry.add(new CountryVo("DE","GERMANY"));
//				listCountry.add(new CountryVo("GH","GHANA"));
//				listCountry.add(new CountryVo("GI","GIBRALTAR"));
//				listCountry.add(new CountryVo("GR","GREECE"));
//				listCountry.add(new CountryVo("GL","GREENLAND"));
//				listCountry.add(new CountryVo("GD","GRENADA"));
//				listCountry.add(new CountryVo("GP","GUADELOUPE"));
//				listCountry.add(new CountryVo("GU","GUAM"));
//				listCountry.add(new CountryVo("GT","GUATEMALA"));
//				listCountry.add(new CountryVo("GG","GUERNSEY"));
//				listCountry.add(new CountryVo("GN","GUINEA"));
//				listCountry.add(new CountryVo("GW","GUINEA_BISSAU"));
//				listCountry.add(new CountryVo("GY","GUYANA"));
//				listCountry.add(new CountryVo("HT","HAITI"));
//				listCountry.add(new CountryVo("HM","HEARD_ISLAND_AND_MCDONALD_ISLANDS"));
//				listCountry.add(new CountryVo("VA","HOLY_SEE_VATICAN_CITY_STATE"));
//				listCountry.add(new CountryVo("HN","HONDURAS"));
//				listCountry.add(new CountryVo("HK","HONG_KONG"));
//				listCountry.add(new CountryVo("HU","HUNGARY"));
//				listCountry.add(new CountryVo("IS","ICELAND"));
				listCountry.add(new CountryVo("IN","India"));
//				listCountry.add(new CountryVo("ID","INDONESIA"));
//				listCountry.add(new CountryVo("IR","IRAN_ISLAMIC_REPUBLIC_OF"));
//				listCountry.add(new CountryVo("IQ","IRAQ"));
//				listCountry.add(new CountryVo("IE","IRELAND"));
//				listCountry.add(new CountryVo("IM","ISLE_OF_MAN"));
//				listCountry.add(new CountryVo("IL","ISRAEL"));
//				listCountry.add(new CountryVo("IT","ITALY"));
//				listCountry.add(new CountryVo("JM","JAMAICA"));
//				listCountry.add(new CountryVo("JP","JAPAN"));
//				listCountry.add(new CountryVo("JE","JERSEY"));
//				listCountry.add(new CountryVo("JO","JORDAN"));
//				listCountry.add(new CountryVo("KZ","KAZAKHSTAN"));
				listCountry.add(new CountryVo("KE","Kenya"));
//				listCountry.add(new CountryVo("KI","KIRIBATI"));
//				listCountry.add(new CountryVo("KP","KOREA_DEMOCRATIC_PEOPLES_REPUBLIC_OF"));
//				listCountry.add(new CountryVo("KR","KOREA_REPUBLIC_OF"));
//				listCountry.add(new CountryVo("KW","KUWAIT"));
//				listCountry.add(new CountryVo("KG","KYRGYZSTAN"));
//				listCountry.add(new CountryVo("LA","LAO_PEOPLES_DEMOCRATIC_REPUBLIC"));
//				listCountry.add(new CountryVo("LV","LATVIA"));
//				listCountry.add(new CountryVo("LB","LEBANON"));
//				listCountry.add(new CountryVo("LS","LESOTHO"));
//				listCountry.add(new CountryVo("LR","LIBERIA"));
//				listCountry.add(new CountryVo("LY","LIBYA"));
//				listCountry.add(new CountryVo("LI","LIECHTENSTEIN"));
//				listCountry.add(new CountryVo("LT","LITHUANIA"));
//				listCountry.add(new CountryVo("LU","LUXEMBOURG"));
//				listCountry.add(new CountryVo("MO","MACAO"));
//				listCountry.add(new CountryVo("MK","MACEDONIA_THE_FORMER_YUGOSLAV_REPUBLIC_OF"));
//				listCountry.add(new CountryVo("MG","MADAGASCAR"));
//				listCountry.add(new CountryVo("MW","MALAWI"));
//				listCountry.add(new CountryVo("MY","MALAYSIA"));
//				listCountry.add(new CountryVo("MV","MALDIVES"));
//				listCountry.add(new CountryVo("ML","MALI"));
//				listCountry.add(new CountryVo("MT","MALTA"));
//				listCountry.add(new CountryVo("MH","MARSHALL_ISLANDS"));
//				listCountry.add(new CountryVo("MQ","MARTINIQUE"));
//				listCountry.add(new CountryVo("MR","MAURITANIA"));
//				listCountry.add(new CountryVo("MU","MAURITIUS"));
//				listCountry.add(new CountryVo("YT","MAYOTTE"));
//				listCountry.add(new CountryVo("MX","MEXICO"));
//				listCountry.add(new CountryVo("FM","MICRONESIA_FEDERATED_STATES_OF"));
//				listCountry.add(new CountryVo("MD","MOLDOVA_REPUBLIC_OF"));
//				listCountry.add(new CountryVo("MC","MONACO"));
//				listCountry.add(new CountryVo("MN","MONGOLIA"));
//				listCountry.add(new CountryVo("ME","MONTENEGRO"));
//				listCountry.add(new CountryVo("MS","MONTSERRAT"));
//				listCountry.add(new CountryVo("MA","MOROCCO"));
//				listCountry.add(new CountryVo("MZ","MOZAMBIQUE"));
//				listCountry.add(new CountryVo("MM","MYANMAR"));
//				listCountry.add(new CountryVo("NA","NAMIBIA"));
//				listCountry.add(new CountryVo("NR","NAURU"));
//				listCountry.add(new CountryVo("NP","NEPAL"));
				listCountry.add(new CountryVo("NL","Netherlands"));
//				listCountry.add(new CountryVo("NC","NEW_CALEDONIA"));
//				listCountry.add(new CountryVo("NZ","NEW_ZEALAND"));
//				listCountry.add(new CountryVo("NI","NICARAGUA"));
//				listCountry.add(new CountryVo("NE","NIGER"));
//				listCountry.add(new CountryVo("NG","NIGERIA"));
//				listCountry.add(new CountryVo("NU","NIUE"));
//				listCountry.add(new CountryVo("NF","NORFOLK_ISLAND"));
//				listCountry.add(new CountryVo("MP","NORTHERN_MARIANA_ISLANDS"));
//				listCountry.add(new CountryVo("NO","NORWAY"));
//				listCountry.add(new CountryVo("OM","OMAN"));
				listCountry.add(new CountryVo("PK","Pakistan"));
//				listCountry.add(new CountryVo("PW","PALAU"));
//				listCountry.add(new CountryVo("PS","PALESTINIAN_TERRITORY_OCCUPIED"));
//				listCountry.add(new CountryVo("PA","PANAMA"));
//				listCountry.add(new CountryVo("PG","PAPUA_NEW_GUINEA"));
//				listCountry.add(new CountryVo("PY","PARAGUAY"));
//				listCountry.add(new CountryVo("PE","PERU"));
//				listCountry.add(new CountryVo("PH","PHILIPPINES"));
//				listCountry.add(new CountryVo("PN","PITCAIRN"));
//				listCountry.add(new CountryVo("PL","POLAND"));
//				listCountry.add(new CountryVo("PT","PORTUGAL"));
//				listCountry.add(new CountryVo("PR","PUERTO_RICO"));
//				listCountry.add(new CountryVo("QA","QATAR"));
//				listCountry.add(new CountryVo("RO","ROMANIA"));
//				listCountry.add(new CountryVo("RU","RUSSIAN_FEDERATION"));
//				listCountry.add(new CountryVo("RW","RWANDA"));
//				listCountry.add(new CountryVo("RE","REUNION"));
//				listCountry.add(new CountryVo("BL","SAINT_BARTHELEMY"));
//				listCountry.add(new CountryVo("SH","SAINT_HELENA_ASCENSION_AND_TRISTAN_DA_CUNHA"));
//				listCountry.add(new CountryVo("KN","SAINT_KITTS_AND_NEVIS"));
//				listCountry.add(new CountryVo("LC","SAINT_LUCIA"));
//				listCountry.add(new CountryVo("MF","SAINT_MARTIN_FRENCH_PART"));
//				listCountry.add(new CountryVo("PM","SAINT_PIERRE_AND_MIQUELON"));
//				listCountry.add(new CountryVo("VC","SAINT_VINCENT_AND_THE_GRENADINES"));
//				listCountry.add(new CountryVo("WS","SAMOA"));
//				listCountry.add(new CountryVo("SM","SAN_MARINO"));
//				listCountry.add(new CountryVo("ST","SAO_TOME_AND_PRINCIPE"));
//				listCountry.add(new CountryVo("SA","SAUDI_ARABIA"));
//				listCountry.add(new CountryVo("SN","SENEGAL"));
//				listCountry.add(new CountryVo("RS","SERBIA"));
//				listCountry.add(new CountryVo("SC","SEYCHELLES"));
//				listCountry.add(new CountryVo("SL","SIERRA_LEONE"));
//				listCountry.add(new CountryVo("SG","SINGAPORE"));
//				listCountry.add(new CountryVo("SX","SINT_MAARTEN_DUTCH_PART"));
//				listCountry.add(new CountryVo("SK","SLOVAKIA"));
//				listCountry.add(new CountryVo("SI","SLOVENIA"));
//				listCountry.add(new CountryVo("SB","SOLOMON_ISLANDS"));
//				listCountry.add(new CountryVo("SO","SOMALIA"));
				listCountry.add(new CountryVo("ZA","South Africa"));
//				listCountry.add(new CountryVo("GS","SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS"));
//				listCountry.add(new CountryVo("SS","SOUTH_SUDAN"));
//				listCountry.add(new CountryVo("ES","SPAIN"));
				listCountry.add(new CountryVo("LK","Sri Lanka"));
//				listCountry.add(new CountryVo("SD","SUDAN"));
//				listCountry.add(new CountryVo("SR","SURINAME"));
//				listCountry.add(new CountryVo("SJ","SVALBARD_AND_JAN_MAYEN"));
//				listCountry.add(new CountryVo("SZ","SWAZILAND"));
//				listCountry.add(new CountryVo("SE","SWEDEN"));
//				listCountry.add(new CountryVo("CH","SWITZERLAND"));
//				listCountry.add(new CountryVo("SY","SYRIAN_ARAB_REPUBLIC"));
//				listCountry.add(new CountryVo("TW","TAIWAN_PROVINCE_OF_CHINA"));
//				listCountry.add(new CountryVo("TJ","TAJIKISTAN"));
//				listCountry.add(new CountryVo("TZ","TANZANIA_UNITED_REPUBLIC_OF"));
//				listCountry.add(new CountryVo("TH","THAILAND"));
//				listCountry.add(new CountryVo("TL","TIMOR_LESTE"));
//				listCountry.add(new CountryVo("TG","TOGO"));
//				listCountry.add(new CountryVo("TK","TOKELAU"));
//				listCountry.add(new CountryVo("TO","TONGA"));
//				listCountry.add(new CountryVo("TT","TRINIDAD_AND_TOBAGO"));
//				listCountry.add(new CountryVo("TN","TUNISIA"));
//				listCountry.add(new CountryVo("TR","TURKEY"));
//				listCountry.add(new CountryVo("TM","TURKMENISTAN"));
//				listCountry.add(new CountryVo("TC","TURKS_AND_CAICOS_ISLANDS"));
//				listCountry.add(new CountryVo("TV","TUVALU"));
//				listCountry.add(new CountryVo("UG","UGANDA"));
//				listCountry.add(new CountryVo("UA","UKRAINE"));
//				listCountry.add(new CountryVo("AE","UNITED_ARAB_EMIRATES"));
				listCountry.add(new CountryVo("GB","United Kingdom"));
				listCountry.add(new CountryVo("US","United States"));
//				listCountry.add(new CountryVo("UM","UNITED_STATES_MINOR_OUTLYING_ISLANDS"));
//				listCountry.add(new CountryVo("UY","URUGUAY"));
//				listCountry.add(new CountryVo("UZ","UZBEKISTAN"));
//				listCountry.add(new CountryVo("VU","VANUATU"));
//				listCountry.add(new CountryVo("VE","VENEZUELA_BOLIVARIAN_REPUBLIC_OF"));
//				listCountry.add(new CountryVo("VN","VIET_NAM"));
//				listCountry.add(new CountryVo("VG","VIRGIN_ISLANDS_BRITISH"));
//				listCountry.add(new CountryVo("VI","VIRGIN_ISLANDS_U_S_"));
//				listCountry.add(new CountryVo("WF","WALLIS_AND_FUTUNA"));
//				listCountry.add(new CountryVo("EH","WESTERN_SAHARA"));
//				listCountry.add(new CountryVo("YE","YEMEN"));
//				listCountry.add(new CountryVo("ZM","ZAMBIA"));
				listCountry.add(new CountryVo("ZW","Zimbabwe"));
	}
}
